# KataGo selfplay training.
# Based off of selfplay training documented at
# https://github.com/lightvector/KataGo/blob/master/SelfplayTraining.md.
#
# Launch command (run from repo root):
# docker-compose -f compose/crash.yml --env-file compose/crash.env up

version: "3"

services:
  selfplay:
    image: humancompatibleai/goattack:cpp
    build:
      context: ..
      dockerfile: ./compose/cpp/Dockerfile
      target: prod
    volumes:
      - type: bind
        source: ${HOST_OUTPUT_DIR}
        target: /outputs
      - type: bind
        source: ${HOST_MODEL_DIR}
        target: /models
      - type: bind
        source: ${HOST_CONFIG_DIR}
        target: /configs
    command: >
      engines/KataGo/cpp/katago selfplay -output-dir /outputs -models-dir /models -config ${CONFIG}
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              driver: nvidia
              device_ids: ["0", "1", "2", "3", "4", "5", "6"]
    cap_add:
      - SYS_PTRACE
    stop_grace_period: 60s
